"""M5 C1 Task 4 — core executor: four cleanup paths + error mapping."""

import asyncio

import pytest
from pydantic import BaseModel

from zygos.errors import ProviderError
from zygos.runtime.context import root_context
from zygos.runtime.events import InProcessEventBus
from zygos.tools.executor import execute_tool
from zygos.tools.types import BaseTool, ToolCall, ToolContext, ToolMeta




class _In(BaseModel):
    x: int


class _Out(BaseModel):
    y: int


def _ctx():
    return root_context(InProcessEventBus())


class SpyTool(BaseTool):
    """Records which phases ran; behavior is parameterized for each path."""

    meta = ToolMeta(name="spy", description="d", input_model=_In, output_model=_Out)

    def __init__(self, *, fail_execute=False, fail_prepare=False, bad_output=False,
                 raise_zygos=False, cleanup_raises=False):
        self.calls: list[str] = []
        self._fail_execute = fail_execute
        self._fail_prepare = fail_prepare
        self._bad_output = bad_output
        self._raise_zygos = raise_zygos
        self._cleanup_raises = cleanup_raises

    def prepare(self, ctx: ToolContext) -> None:
        self.calls.append("prepare")
        if self._fail_prepare:
            raise RuntimeError("prepare boom")

    async def execute(self, input: _In, ctx: ToolContext):
        self.calls.append("execute")
        if self._raise_zygos:
            raise ProviderError("zygos boom", provider="p")
        if self._fail_execute:
            raise RuntimeError("execute boom")
        if self._bad_output:
            return {"wrong": "shape"}
        return _Out(y=input.x)

    def cleanup(self, ctx: ToolContext) -> None:
        self.calls.append("cleanup")
        if self._cleanup_raises:
            raise RuntimeError("cleanup boom")


@pytest.mark.asyncio
async def test_happy_path_ok_and_cleanup_ran():
    tool = SpyTool()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 5}), _ctx())
    assert res.ok is True and res.output == _Out(y=5)
    assert tool.calls == ["prepare", "execute", "cleanup"]


@pytest.mark.asyncio
async def test_execute_raises_maps_to_execution_failed_and_cleanup_ran():
    tool = SpyTool(fail_execute=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_execution_failed"
    assert "cleanup" in tool.calls


@pytest.mark.asyncio
async def test_verify_fail_maps_to_verify_failed_and_cleanup_ran():
    tool = SpyTool(bad_output=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_verify_failed"
    assert "cleanup" in tool.calls


@pytest.mark.asyncio
async def test_prepare_raises_and_cleanup_ran():
    tool = SpyTool(fail_prepare=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_execution_failed"
    assert tool.calls == ["prepare", "cleanup"]  # execute never ran


@pytest.mark.asyncio
async def test_bad_args_returns_input_invalid_without_prepare_or_cleanup():
    tool = SpyTool()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": "not-int"}), _ctx())
    assert res.ok is False and res.error_code == "tool_input_invalid"
    assert tool.calls == []  # neither prepare nor cleanup ran


@pytest.mark.asyncio
async def test_zygos_error_code_is_propagated():
    tool = SpyTool(raise_zygos=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "provider_error"  # ProviderError.code


@pytest.mark.asyncio
async def test_cleanup_raises_after_success_downgrades_result():
    tool = SpyTool(cleanup_raises=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_cleanup_failed"


@pytest.mark.asyncio
async def test_cleanup_raises_after_failure_preserves_primary_error():
    tool = SpyTool(fail_execute=True, cleanup_raises=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_execution_failed"  # not cleanup_failed


@pytest.mark.asyncio
async def test_call_id_autogenerated_when_absent():
    tool = SpyTool()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.call_id and isinstance(res.call_id, str)


@pytest.mark.asyncio
async def test_call_id_echoed_when_provided():
    tool = SpyTool()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}, call_id="fixed-id"), _ctx())
    assert res.call_id == "fixed-id"


class SlowTool(BaseTool):
    """execute sleeps past the tool's timeout_s."""

    meta = ToolMeta(name="slow", description="d", input_model=_In, output_model=_Out,
                    timeout_s=0.01)

    def __init__(self):
        self.calls: list[str] = []

    async def execute(self, input: _In, ctx: ToolContext):
        self.calls.append("execute")
        await asyncio.sleep(1.0)   # far exceeds 0.01s timeout
        return _Out(y=input.x)

    def cleanup(self, ctx: ToolContext) -> None:
        self.calls.append("cleanup")


@pytest.mark.asyncio
async def test_timeout_maps_to_tool_timeout_and_cleanup_ran():
    tool = SlowTool()
    res = await execute_tool(tool, ToolCall(tool="slow", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_timeout"
    assert "cleanup" in tool.calls


@pytest.mark.asyncio
async def test_default_timeout_applies_when_meta_timeout_none():
    # A fast tool with timeout_s=None must still succeed (default 60s path, not 0).
    tool = SpyTool()  # meta has no timeout_s -> None
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 3}), _ctx())
    assert res.ok is True and res.output == _Out(y=3)


from zygos.errors import ToolError
from zygos.tools.types import RetryPolicy


class _Retry(ToolError):
    code = "x_retry"
    retryable = True


class FlakyTool(BaseTool):
    """Raises a retryable error `fail_times` times, then succeeds."""

    def __init__(self, *, fail_times: int, attempts: int):
        self.meta = ToolMeta(name="flaky", description="d", input_model=_In, output_model=_Out,
                             retry=RetryPolicy(attempts=attempts, backoff_ms=250, multiplier=2.0))
        self._fail_times = fail_times
        self.execute_calls = 0
        self.cleanup_calls = 0

    async def execute(self, input: _In, ctx: ToolContext):
        self.execute_calls += 1
        if self.execute_calls <= self._fail_times:
            raise _Retry("transient")
        return _Out(y=input.x)

    def cleanup(self, ctx: ToolContext) -> None:
        self.cleanup_calls += 1


def _fake_sleep():
    calls: list[float] = []

    async def sleep(s: float) -> None:
        calls.append(s)

    return sleep, calls


@pytest.mark.asyncio
async def test_retry_succeeds_after_transient_failures_with_backoff():
    tool = FlakyTool(fail_times=2, attempts=3)
    sleep, slept = _fake_sleep()
    res = await execute_tool(tool, ToolCall(tool="flaky", args={"x": 9}), _ctx(), sleep=sleep)
    assert res.ok is True and res.output == _Out(y=9)
    assert tool.execute_calls == 3
    assert tool.cleanup_calls == 3          # cleanup ran every attempt
    assert slept == [0.25, 0.5]             # 250ms, then 250*2ms — exponential backoff


@pytest.mark.asyncio
async def test_retry_exhausted_returns_last_failure():
    tool = FlakyTool(fail_times=5, attempts=2)
    sleep, slept = _fake_sleep()
    res = await execute_tool(tool, ToolCall(tool="flaky", args={"x": 1}), _ctx(), sleep=sleep)
    assert res.ok is False and res.error_code == "x_retry"
    assert tool.execute_calls == 2 and slept == [0.25]


@pytest.mark.asyncio
async def test_non_retryable_error_not_retried():
    tool = SpyTool(fail_execute=True)   # RuntimeError -> tool_execution_failed (not retryable)
    tool.meta = ToolMeta(name="spy", description="d", input_model=_In, output_model=_Out,
                         retry=RetryPolicy(attempts=3))
    sleep, slept = _fake_sleep()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx(), sleep=sleep)
    assert res.ok is False and res.error_code == "tool_execution_failed"
    assert slept == []                   # never retried


@pytest.mark.asyncio
async def test_cancelled_returns_tool_cancelled_without_running():
    tool = SpyTool()
    ctx = _ctx()
    ctx._cancel.trip()                   # trip the parent cancel token
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), ctx)
    assert res.ok is False and res.error_code == "tool_cancelled"
    assert tool.calls == []              # no phase ran
