"""M5 C1 Task 4 — core executor: four cleanup paths + error mapping."""

import pytest
from pydantic import BaseModel

from zygos.errors import ProviderError
from zygos.runtime.context import root_context
from zygos.runtime.events import InProcessEventBus
from zygos.tools.executor import execute_tool
from zygos.tools.types import BaseTool, ToolCall, ToolContext, ToolMeta, VerifyResult


class _In(BaseModel):
    x: int


class _Out(BaseModel):
    y: int


def _ctx():
    return root_context(InProcessEventBus())


class SpyTool(BaseTool):
    """Records which phases ran; behavior is parameterized for each path."""

    meta = ToolMeta(name="spy", description="d", input_model=_In, output_model=_Out)

    def __init__(self, *, fail_execute=False, fail_prepare=False, bad_output=False,
                 raise_zygos=False, cleanup_raises=False):
        self.calls: list[str] = []
        self._fail_execute = fail_execute
        self._fail_prepare = fail_prepare
        self._bad_output = bad_output
        self._raise_zygos = raise_zygos
        self._cleanup_raises = cleanup_raises

    def prepare(self, ctx: ToolContext) -> None:
        self.calls.append("prepare")
        if self._fail_prepare:
            raise RuntimeError("prepare boom")

    async def execute(self, input: _In, ctx: ToolContext):
        self.calls.append("execute")
        if self._raise_zygos:
            raise ProviderError("zygos boom", provider="p")
        if self._fail_execute:
            raise RuntimeError("execute boom")
        if self._bad_output:
            return {"wrong": "shape"}
        return _Out(y=input.x)

    def cleanup(self, ctx: ToolContext) -> None:
        self.calls.append("cleanup")
        if self._cleanup_raises:
            raise RuntimeError("cleanup boom")


@pytest.mark.asyncio
async def test_happy_path_ok_and_cleanup_ran():
    tool = SpyTool()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 5}), _ctx())
    assert res.ok is True and res.output == _Out(y=5)
    assert tool.calls == ["prepare", "execute", "cleanup"]


@pytest.mark.asyncio
async def test_execute_raises_maps_to_execution_failed_and_cleanup_ran():
    tool = SpyTool(fail_execute=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_execution_failed"
    assert "cleanup" in tool.calls


@pytest.mark.asyncio
async def test_verify_fail_maps_to_verify_failed_and_cleanup_ran():
    tool = SpyTool(bad_output=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_verify_failed"
    assert "cleanup" in tool.calls


@pytest.mark.asyncio
async def test_prepare_raises_and_cleanup_ran():
    tool = SpyTool(fail_prepare=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_execution_failed"
    assert tool.calls == ["prepare", "cleanup"]  # execute never ran


@pytest.mark.asyncio
async def test_bad_args_returns_input_invalid_without_prepare_or_cleanup():
    tool = SpyTool()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": "not-int"}), _ctx())
    assert res.ok is False and res.error_code == "tool_input_invalid"
    assert tool.calls == []  # neither prepare nor cleanup ran


@pytest.mark.asyncio
async def test_zygos_error_code_is_propagated():
    tool = SpyTool(raise_zygos=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "provider_error"  # ProviderError.code


@pytest.mark.asyncio
async def test_cleanup_raises_after_success_downgrades_result():
    tool = SpyTool(cleanup_raises=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_cleanup_failed"


@pytest.mark.asyncio
async def test_cleanup_raises_after_failure_preserves_primary_error():
    tool = SpyTool(fail_execute=True, cleanup_raises=True)
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.ok is False and res.error_code == "tool_execution_failed"  # not cleanup_failed


@pytest.mark.asyncio
async def test_call_id_autogenerated_when_absent():
    tool = SpyTool()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}), _ctx())
    assert res.call_id and isinstance(res.call_id, str)


@pytest.mark.asyncio
async def test_call_id_echoed_when_provided():
    tool = SpyTool()
    res = await execute_tool(tool, ToolCall(tool="spy", args={"x": 1}, call_id="fixed-id"), _ctx())
    assert res.call_id == "fixed-id"
